name: Workflow
on: [push]
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        go_version: [ "1.22" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: go/src/github.com/dnbsd/jsonrpc
      - uses: actions/setup-go@v2
        with:
          go-version: "${{ matrix.go_version }}"
      - run: make test
        working-directory: go/src/github.com/dnbsd/jsonrpc